name: Work Stats Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every 2 hours
    - cron: "5 * * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@v0.3.0
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TIME: "True"
          SHOW_TOTAL: "True"
          LANG_COUNT: 5
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          SECTION_NAME: waka
          TIME_RANGE: last_30_days
